export default `Johannesburg, South Africa: 15 July, 2020 – Microsoft has announced the expansion of its award-winning Surface device range into South Africa, with the introduction of the Surface Pro 7 and Surface Laptop 3 for both commercial and consumer customers. The devices will be available for consumers in retail from Incredible Connection stores and Vodacom from 29 July.
The Surface Pro 7 and Surface Laptop 3 continue the brand’s tradition of best-in-class productivity, security, mobility and speed, and introduce new processors and modern connectivity options in a world of remote work and learning.
“Rapid and continuous change define modern living and working – and the shift to remote working and education requires the right tools to stay productive and connected securely,” said Vithesh Reddy, Consumer and Channel Marketing Director at Microsoft South Africa. “Microsoft’s Surface family is designed for just that kind of versatility, portability and productivity, so people can work and play faster, better, and stay connected wherever they are. As with previous Surface devices, we have delivered best-in-class upgrades for our new additions to the family, to ensure that individuals and organisations have access to the optimal performance they need to achieve more in the office, classroom, or out in the field.”
The Surface Pro 7 takes Microsoft’s iconic 2-in-1 design to the next level, with a faster and more versatile device for professionals on the go. Powered by a 10th Generation Intel® Core™ processor, Fast Charging, all-day battery1 and Instant On, the Surface Pro 7 provides modern connectivity with USB-C™ and USB-A ports.
Businesses and consumers across South Africa will also have access to the latest edition of Microsoft’s most beloved laptop series. The new Surface Laptop 3 makes a statement though a thin, light, and elegant design, offering rich tone-on-tone colour options and new metal keyboard finishes. Surface Laptop 3 is now available in two sizes – 13.5-inch and 15-inch and features a vibrant PixelSense™ Display touchscreen. The device delivers improved speed and performance with the latest 10th Generation Intel® Core™ processor, up to 11.5 hours battery life2, and Instant On. The Surface Laptop 3 15-inch consumer offering is powered by the AMD Ryzen™ Surface Edition processor.
“The Surface family has always transcended market expectations – whether in the consumer or corporate segment – providing devices at the leading edge of innovation, and establishing new benchmarks for excellence,” said Reddy. “At each iteration, we elevate the entire Microsoft ecosystem, ensuring our devices evolve into a line of products that cover the widest possible range of individual and business use cases – versatile, adaptable, powerful and secure to enable remote working or schooling.”
Adds Gary Pickford, CCO at Tarsus Distribution, “We’re excited to introduce the Surface Laptop 3 and Surface Pro 7 products to the South African market, offering a new, Windows-powered alternative in the premium mobile segment. The models we are providing to our channel offer a blend of speed, style and versatility for notebook and tablet users looking for a Windows device with a high-quality finish and a device that balances security, aesthetics, speed and versatility.”
Recommended retail pricing for the Surface Pro 7 starts at R17 999.00, and for the Surface Laptop 3 starts at R22 999.00.
To find out more about support, warranties and extended warranties on Surface devices, please visit https://support.microsoft.com/en-ZA or call 0860 22 55 67 weekdays 9am – 9pm and weekends ​10am – 6pm.
1 Up to 10.5 hours of battery life based on typical Surface device usage. Testing conducted by Microsoft in September 2019 using preproduction software and preproduction Intel® Core™ i5, 256GB, 8 GB RAM device. Battery life varies significantly with settings, usage and other factors. See surface.com.
2Up to 11.5 hours of battery life based on typical Surface device usage. Testing conducted by Microsoft in September 2019 using preproduction software and preproduction 13.5” Intel® Core™ i5, 256GB, 8 GB RAM and 15” AMD Ryzen™ 5 3580U Mobile Processor with Radeon™ Vega 9 Graphics Microsoft Surface® Edition devices. Battery life varies significantly with settings, usage and other factors.  See surface.com.`;
